name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: gcr.io/cloud-builders/docker
        args:
          - build
          - '-t'
          - 'gcr.io/{{env.PROJECT_ID}}/{{env.GCR_REPOSITORY}}:$COMMIT_SHA'
          - .
        id: Build Container Image
      - name: gcr.io/cloud-builders/docker
        args:
          - push
          - 'gcr.io/{{env.PROJECT_ID}}/{{env.GCR_REPOSITORY}}:$COMMIT_SHA'
        id: Push Image to Container Registry
      - name: gcr.io/cloud-builders/gcloud
        args:
          - run
          - deploy
          - { { env.SERVICE_NAME } }
          - '--image'
          - 'gcr.io/{{env.PROJECT_ID}}/{{env.GCR_REPOSITORY}}:$COMMIT_SHA'
          - '--region'
          - us-central1
          - '--platform'
          - managed
        id: Deploy Container on Google Cloud Run
    images:
      - 'gcr.io/{{env.PROJECT_ID}}/{{env.GCR_REPOSITORY}}:$COMMIT_SHA'
